### ISSUE TITLE
Not working in Angular 20

### ISSUE THREAD

**Issue by jatingarala** [valor-software/ng2-charts#2013]
[ERROR] TS2307: Cannot find module 'chart.js/dist/types/utils' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/ng2-charts/lib/ng-charts.provider.d.ts:3:28:
      3 │ import { DeepPartial } from 'chart.js/dist/types/utils';
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~

I get above error when update angular to 20, I am using latest ng2-charts version

"ng2-charts": "^8.0.0",
"chart.js": "^4.4.9",

Request to update version to support Angular 20.

Thank you

![Image](https://github.com/user-attachments/assets/abdaf9bc-9abf-4749-9b98-a161cfb9c1ec)

**Comment by docaohuynhcse** [comment]
> Short term fix, add skip type-checking of declaration files (.d.ts files), to your `tsconfig.json`:
> 
> ```
> {
>   "compilerOptions": {
>     "skipLibCheck": true
> },
> ```

This fixed it for me. tks

**Comment by basrieter** [comment]
I used `patch-package` to patch `ng-charts.provider.d.ts` to make it work again.

**Comment by zijianhuang** [comment]
> I used `patch-package` to patch `ng-charts.provider.d.ts` to make it work again.

@basrieter 
Can you please describe how to use  `patch-package` to patch `ng-charts.provider.d.ts` ?

for example, do I need to fork the repos, and rebuild using Angular 19, etc. ?

**Comment by ZuBB** [comment]
my 5c on this: this issue (compile error) has nothing to do with angular 20. matching of angular's versrions between your app (probably v20) and peer deps of this package is separate issue.

problem we see here already has been filled as #1991.

imho this should be closed in favor of it
